### PR TITLE
#38 #37

### LINKED ISSUE #37: Response header fields not logged
First, thanks for this great project !

Hapi: 18.4.0
laabr: 5.1.2

Only `-` you see as output on any response header field. I.e.: `:res[cache-control]`

After debugging I've found that it is because `data.res.header` is undefined.
Hapi has `headers` object in response, so using similar code as in `req`, solves issue.

I will do PR with this.

### LINKED ISSUE #38: Missing console.debug binding
There is no binding for `console.debug`

I will do PR with this.

### PR DESCRIPTION
**Pull request by jedrus2000**
fix #38 
fix #37

### CODE REVIEW

**Comment by felixheck** [comment]
Hi Andrzej,
thanks a lot a) for using the plugin b) the opened issues c) your efforts for fixing those 🙏 
Highly appreciate it!

I'll take a look at it tomorrow morning, merge & release the patch.
Have a great evening :)

**Comment by jedrus2000** [comment]
Thanks for such nice words ! This project is really very valuable - it makes logging in Hapi easy and complete.

Coverage percentage is now lowered because `getHeader` is not used/involved in tests.

**Comment by felixheck** [comment]
Actually the only usage of `getHeader` got removed.
Would you mind removing the function in `utils.js` as well? 

Happy to release it afterwards :🙏🏽

**Comment by jedrus2000** [comment]
> Actually the only usage of `getHeader` got removed.
> Would you mind removing the function in `utils.js` as well?
> 
> Happy to release it afterwards :🙏🏽

Sure. Done.

**Comment by felixheck** [comment]
thanks a lot!
Published as `5.1.3`

**Pull request merged**
